# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

import PyQt4.QtCore as QtCore
import PyQt4.QtGui as QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1211, 397)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 81))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.btnAudio = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.btnAudio.setObjectName(_fromUtf8("btnAudio"))
        self.horizontalLayout.addWidget(self.btnAudio)
        self.btnImagen = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.btnImagen.setObjectName(_fromUtf8("btnImagen"))
        self.horizontalLayout.addWidget(self.btnImagen)
        self.btnVideo = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.btnVideo.setObjectName(_fromUtf8("btnVideo"))
        self.horizontalLayout.addWidget(self.btnVideo)
        self.btnArchivo = QtGui.QPushButton(self.centralwidget)
        self.btnArchivo.setGeometry(QtCore.QRect(10, 120, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnArchivo.setFont(font)
        self.btnArchivo.setObjectName(_fromUtf8("btnArchivo"))
        self.btnProcesar = QtGui.QPushButton(self.centralwidget)
        self.btnProcesar.setGeometry(QtCore.QRect(780, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnProcesar.setFont(font)
        self.btnProcesar.setObjectName(_fromUtf8("btnProcesar"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 751, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.sliderUmbral = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.sliderUmbral.setMaximum(100)
        self.sliderUmbral.setSingleStep(1)
        self.sliderUmbral.setPageStep(1)
        self.sliderUmbral.setProperty("value", 0)
        self.sliderUmbral.setTracking(True)
        self.sliderUmbral.setOrientation(QtCore.Qt.Horizontal)
        self.sliderUmbral.setObjectName(_fromUtf8("sliderUmbral"))
        self.horizontalLayout_2.addWidget(self.sliderUmbral)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(780, 110, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(590, 10, 311, 80))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.btnSiGrabar = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnSiGrabar.setFont(font)
        self.btnSiGrabar.setObjectName(_fromUtf8("btnSiGrabar"))
        self.horizontalLayout_3.addWidget(self.btnSiGrabar)
        self.btnNoGrabar = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnNoGrabar.setFont(font)
        self.btnNoGrabar.setObjectName(_fromUtf8("btnNoGrabar"))
        self.horizontalLayout_3.addWidget(self.btnNoGrabar)
        self.btnSalir = QtGui.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(1000, 210, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSalir.setFont(font)
        self.btnSalir.setObjectName(_fromUtf8("btnSalir"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(910, 10, 291, 80))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.btnSiCamara = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.btnSiCamara.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnSiCamara.setFont(font)
        self.btnSiCamara.setCheckable(True)
        self.btnSiCamara.setObjectName(_fromUtf8("btnSiCamara"))
        self.horizontalLayout_4.addWidget(self.btnSiCamara)
        self.btnNoCamara = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnNoCamara.setFont(font)
        self.btnNoCamara.setObjectName(_fromUtf8("btnNoCamara"))
        self.horizontalLayout_4.addWidget(self.btnNoCamara)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(240, 110, 521, 80))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.btnNormalClone = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnNormalClone.setFont(font)
        self.btnNormalClone.setObjectName(_fromUtf8("btnNormalClone"))
        self.horizontalLayout_5.addWidget(self.btnNormalClone)
        self.btnMixedClone = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnMixedClone.setFont(font)
        self.btnMixedClone.setObjectName(_fromUtf8("btnMixedClone"))
        self.horizontalLayout_5.addWidget(self.btnMixedClone)
        self.btnPlay = QtGui.QPushButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(310, 290, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btnPlay.setFont(font)
        self.btnPlay.setObjectName(_fromUtf8("btnPlay"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.btnPause = QtGui.QPushButton(self.centralwidget)
        self.btnPause.setGeometry(QtCore.QRect(390, 290, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btnPause.setFont(font)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.sliderUmbral, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_6.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Panel de control - Aplicación de realidad aumentada - Andrés David Liu Fong, Kevin Alexis Carrillo Acosta, Leonel Giraldo Londoño", None))
        self.label.setText(_translate("MainWindow", "1) Opciones para aumentar el video", None))
        self.btnAudio.setText(_translate("MainWindow", "Audio", None))
        self.btnImagen.setText(_translate("MainWindow", "Imagen", None))
        self.btnVideo.setText(_translate("MainWindow", "Video", None))
        self.btnArchivo.setText(_translate("MainWindow", "4) Escoger archivo", None))
        self.btnProcesar.setText(_translate("MainWindow", "Procesar", None))
        self.label_5.setText(_translate("MainWindow", "6) Umbral:", None))
        self.label_6.setText(_translate("MainWindow", "0", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400;\">Defina TODAS las opciones en el orden indicado antes de presionar el botón \'Procesar\'.</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "2) ¿Grabar video aumentado?", None))
        self.btnSiGrabar.setText(_translate("MainWindow", "Sí", None))
        self.btnNoGrabar.setText(_translate("MainWindow", "No", None))
        self.btnSalir.setText(_translate("MainWindow", "Salir", None))
        self.label_8.setText(_translate("MainWindow", "3) ¿Utilizar una cámara?", None))
        self.btnSiCamara.setText(_translate("MainWindow", "Sí", None))
        self.btnNoCamara.setText(_translate("MainWindow", "No", None))
        self.label_9.setText(_translate("MainWindow", "5) Tipo de sobreposición", None))
        self.btnNormalClone.setText(_translate("MainWindow", "cv2.NORMAL_CLONE", None))
        self.btnMixedClone.setText(_translate("MainWindow", "cv2.MIXED_CLONE", None))
        self.btnPlay.setText(_translate("MainWindow", "►", None))
        self.label_10.setText(_translate("MainWindow", "  Controles para la reproducción:", None))
        self.btnPause.setText(_translate("MainWindow", "  ▌▌", None))

